const std = @import("std");

// main.zig: USER code.
//
// Example generated by protobuzig --ws. Modify it freely to put your
// own problem logic here: create messages, fill fields, write to file,
// change format, etc.
//
// The generated code lives in src/runtime:
//
//     Bon.zig       RAW implementation (internal use; do not import it)
//     Bon_api.zig   SAFE API over the raw: use THIS one
//     encdec.zig         serialization support
//
//     const Bon = @import("runtime/Bon_api.zig");
//
// The namespace carries the name of the CONTRACT (the .proto file name) and
// the example message is the FIRST message defined in it.
const Bon = @import("runtime/Bon_api.zig");
const Cia = Bon.Cia;   // the first message of the contract

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const a = gpa.allocator();

    // 1) Create an object of the contract message.
    var msg = try Cia.initDefault(a);
    defer msg.deinit(a);

    // Set a sample value in the first field ("name") with the safe API:
    // remove this and put your own logic.
    try msg.setName(a, "valor de ejemplo");


    // 2) Write it to file as Protobuf Text and read it back.
    try msg.writeToFile(a, "demo.txt", .TF_PROTOBUF);
    var desde_texto = try Cia.readFromFile(a, "demo.txt", .TF_PROTOBUF);
    defer desde_texto.deinit(a);

    // 3) Change format: Protocol Buffers binary, and read it back.
    try msg.serializeToFile(a, "demo.pb", .BF_PROTOBUF);
    var desde_binario = try Cia.deserializeFromFile(a, "demo.pb", .BF_PROTOBUF);
    defer desde_binario.deinit(a);

    // 4) Show the content on the console.
    const texto = try msg.writeToText(a, .TF_PROTOBUF);
    defer a.free(texto);
    std.debug.print("{s}\n", .{texto});

    std.debug.print("Demo ok: check demo.txt and demo.pb in the current directory.\n", .{});
}
