const std = @import("std");
const t = std.testing;

// tests.zig: one round-trip test (Protobuf Text + binary) per EXTERNAL
// message of the contract (2); nested ones are not tested here.
// Generated by protobuzig --ws: if you add messages to the .proto,
// regenerate the workspace.

// Generated safe API (Bon_api.zig), not the raw one. The wrappers live
// at the top level of the file (without the proto package) and the
// namespace carries the name of the CONTRACT (the .proto file name).
const Bon = @import("runtime/Bon_api.zig");

fn ronda(comptime T: type) !void {
    const a = t.allocator;

    var msg = try T.initDefault(a);
    defer msg.deinit(a);

    // Protobuf Text: write and read back.
    const teksto = try msg.writeToText(a, .TF_PROTOBUF);
    defer a.free(teksto);
    var reteksto = try T.readFromText(a, teksto, .TF_PROTOBUF);
    defer reteksto.deinit(a);

    // Protocol Buffers binary: write and read back.
    const binara = try msg.serializeToBin(a, .BF_PROTOBUF);
    defer a.free(binara);
    var rebinara = try T.deserializeFromBin(a, binara, .BF_PROTOBUF);
    defer rebinara.deinit(a);
}

test "Cia: round-trip texto + binario" {
    try ronda(Bon.Cia);
}

test "Bon: round-trip texto + binario" {
    try ronda(Bon.Bon);
}
