syntax = "proto2";
package k6bus.security;
option optimize_for = SPEED;

// ---------------------------------------------------------------------
// Algoritmos soportados
// ---------------------------------------------------------------------
enum CryptoMode {
    CRYPTO_NONE              = 0;
    CRYPTO_AES_256_GCM       = 1;
    CRYPTO_CHACHA20_POLY1305 = 2;
    CRYPTO_AES_256_CBC       = 3;
}

// ---------------------------------------------------------------------
// Registro de clave
// ---------------------------------------------------------------------

message KeyRecord {
    optional uint32 version = 1 	[default = 1];
    optional string description = 2;
    optional CryptoMode mode = 3	[default = CRYPTO_AES_256_GCM];
    optional uint32 key_id = 4 		[default = 0];

    // Siempre almacenada en texto Base64.
    required string key = 5;

    // Sólo utilizado por AES-CBC.
    optional string iv = 6;
}

//message KeyRegistry {
//}