const std = @import("std");
const k6bus = @import("k6bus");

const generic_pubsub = @import("generic_pubsub.zig");

const Msg = k6bus.Msg;
const Utils = k6bus.MsgUtils;
const BinaryFormat = k6bus.Config.BinaryFormat;
const ifcSubscriber = k6bus.ifcSubscriber;

// ============================================================================
// HELPERS
// ============================================================================
// Types generated by the safe API contain:
//     impl: DatumRaw
// SafePublisher uses the internal raw value to delegate to GenericPublisher.
// SafeSubscriber uses the raw type to compute the same msgType as the raw
// version, but deserializes a DatumApi directly.
// ============================================================================
fn RawType(comptime DatumApi: type) type {
    if (!@hasField(DatumApi, "impl")) {
        @compileError(
            @typeName(DatumApi) ++
                " does not have the 'impl' field required by safe_pubsub",
        );
    }

    return @FieldType(DatumApi, "impl");
}

// ============================================================================
// FORMAT CONVERSION
// ============================================================================
// Config.BinaryFormat and the BinaraFormato generated by ProtobuZig are
// different enums even though they share the same values.
// This conversion keeps the format configured in Domain.
// ============================================================================
fn binaryFormatToBinaraFormato(comptime BinaraFormato: type, value: BinaryFormat) BinaraFormato {
    return std.meta.intToEnum(
        BinaraFormato,
        @intFromEnum(value),
    ) catch .BF_PROTOBUF;
}

// ============================================================================
// SAFE PUBLISHER
// ============================================================================
// SafePublisher is a generic wrapper over GenericPublisher.
// DatumApi:
//     Wrapper generated in <package>_api.zig.
// DatumRaw:
//     Type derived from DatumApi.impl.
// Publishing:
//     - receives a DatumApi;
//     - lends &datum.impl to the GenericPublisher;
//     - does not modify DatumApi;
//     - does not take ownership of DatumApi;
//     - reuses the whole raw serialization and send flow.
// ============================================================================
pub fn SafePublisher(comptime DatumApi: type, comptime BinaraFormato: type) type {
    const DatumRaw = RawType(DatumApi);

    const GenericPublisherType =
        generic_pubsub.GenericPublisher(
            DatumRaw,
            BinaraFormato,
        );

    return struct {
        generic_publisher: GenericPublisherType,

        const Self = @This();

        // --------------------------------------------------------------------
        // CREATE
        // --------------------------------------------------------------------
        pub fn create(domain: *k6bus.Domain) !Self {
            return .{
                .generic_publisher = try GenericPublisherType.create(domain),
            };
        }

        // --------------------------------------------------------------------
        // PUBLISH
        // --------------------------------------------------------------------
        pub fn publish(
            self: *Self,
            channel_name: []const u8,
            datum: *const DatumApi,
        ) !bool {
            return try self.generic_publisher.publish(
                channel_name,
                &datum.impl,
            );
        }

        // --------------------------------------------------------------------
        // PUBLISH TO CHANNELS
        // --------------------------------------------------------------------
        pub fn publishToChannels(
            self: *Self,
            channel_names: []const []const u8,
            datum: *const DatumApi,
        ) !bool {
            return try self.generic_publisher.publishToChannels(
                channel_names,
                &datum.impl,
            );
        }
    };
}

// ============================================================================
// SAFE SUBSCRIBER
// ============================================================================
// SafeSubscriber is a self-contained generic implementation.
// It is based on the structure and the contracts of GenericSubscriber, but:
//     - it works directly with DatumApi;
//     - it stores a safe callback;
//     - it deserializes through DatumApi.deserializeFromBin();
//     - it delivers only types of the safe API.
// The object registered in Domain is directly SafeSubscriber.
// There is no:
//     - internal GenericSubscriber;
//     - additional wrapper;
//     - comptime callback;
//     - global context;
//     - shallow view of the raw datum.
// DatumApi is temporarily owned by SafeSubscriber during the callback.
// The callback:
//     - must not call datum.deinit();
//     - must not keep datum or its internal slices;
//     - may call datum.clone() if it needs to keep an owned copy.
// ============================================================================
pub fn SafeSubscriber(comptime DatumApi: type, comptime BinaraFormato: type) type {
    const DatumRaw = RawType(DatumApi);

    return struct {
        // --------------------------------------------------------------------
        // CALLBACK
        // --------------------------------------------------------------------
        pub const DatumCallback = *const fn (
            allocator: std.mem.Allocator,
            channel_name: []const u8,
            datum: *const DatumApi,
        ) void;

        // --------------------------------------------------------------------
        // STATE
        // --------------------------------------------------------------------
        domain: *k6bus.Domain,

        name: []const u8,
        channel_name: []const u8,

        channel: u64,
        msgType: u64,

        callback: DatumCallback,

        qm: k6bus.QueueMgr,

        binary_format: BinaraFormato = .BF_PROTOBUF,

        const Self = @This();

        // --------------------------------------------------------------------
        // CREATE
        // --------------------------------------------------------------------
        pub fn create(
            domain: *k6bus.Domain,
            channel_name: []const u8,
            callback: DatumCallback,
        ) !*Self {
            const self = try domain.allocator.create(Self);
            errdefer domain.allocator.destroy(self);

            try self.init(domain, channel_name, callback);

            return self;
        }

        // --------------------------------------------------------------------
        // INIT
        // --------------------------------------------------------------------
        fn init(
            self: *Self,
            domain: *k6bus.Domain,
            channel_name: []const u8,
            callback: DatumCallback,
        ) !void {
            const allocator = domain.allocator;

            self.domain = domain;
            self.callback = callback;

            self.channel_name =
                try allocator.dupe(u8, channel_name);
            errdefer allocator.free(self.channel_name);

            self.channel = k6bus.Hash.hashChannel(channel_name);

            // The hash is computed with DatumRaw to keep interoperability
            // between raw and safe publishers and subscribers.
            self.msgType = k6bus.Hash.hashMsgType(domain.id, @typeName(DatumRaw));

            self.binary_format =
                binaryFormatToBinaraFormato(BinaraFormato, domain.dom_cfg.binary_format);

            const id = @intFromPtr(self) >> 4 & 0xFFFF;
            self.name = try std.fmt.allocPrint(
                allocator,
                "{s}SafeSubscriber_{X:0>4}",
                .{
                    @typeName(DatumRaw),
                    id,
                },
            );
            errdefer allocator.free(self.name);

            self.qm = try k6bus.QueueMgr.create(
                domain,
                self.name,
                domain.dom_cfg.dispatch_mode,
                @intCast(
                    domain.dom_cfg.dispatch_batch_time_ms,
                ),
                self,
                dispatchMsg,
            );
            errdefer self.qm.close();

            const subscriber_ifc = self.subscriber();

            try domain.registerSubscriber(self.channel, self.msgType, subscriber_ifc);
            errdefer domain.unregisterSubscriber(subscriber_ifc);

            if (domain.dom_cfg.start_at_init) {
                try self.start();
            }
        }

        // --------------------------------------------------------------------
        // DEINIT
        // --------------------------------------------------------------------
        fn deinit(self: *Self) void {
            const allocator = self.domain.allocator;

            allocator.free(self.name);
            allocator.free(self.channel_name);
        }

        // --------------------------------------------------------------------
        // DISPATCH
        // --------------------------------------------------------------------
        // QueueMgr transfers to dispatchMsg the ownership of the Msg held
        // in msg_list.
        // Each Msg is freed exactly once through Utils.freeMsg().
        // The deserialized DatumApi temporarily belongs to this function
        // and is destroyed after running the callback.
        // --------------------------------------------------------------------
        fn dispatchMsg(owner: *anyopaque, msg_list: []const Msg) void {
            const self: *Self = @ptrCast(@alignCast(owner));

            const allocator = self.domain.allocator;

            for (msg_list) |*msg| {
                defer Utils.freeMsg(allocator, @constCast(msg));

                // if (msg.msgType != self.msgType) { continue;}

                var datum =
                    DatumApi.deserializeFromBin(
                        allocator,
                        msg.payLoad,
                        self.binary_format,
                    ) catch |err| {
                        self.domain.logger.warning(
                            "{s} failed to deserialize {s}: {}",
                            .{
                                self.name,
                                @typeName(DatumRaw),
                                err,
                            },
                            @src(),
                        );

                        continue;
                    };
                defer datum.deinit(allocator);

                self.callback(allocator, self.channel_name, &datum);
            }
        }

        // --------------------------------------------------------------------
        // START
        // --------------------------------------------------------------------
        pub fn start(self: *Self) !void {
            try self.qm.start();
        }

        // --------------------------------------------------------------------
        // STOP
        // --------------------------------------------------------------------
        pub fn stop(self: *Self) void {
            self.qm.stop();
        }

        // --------------------------------------------------------------------
        // CLOSE
        // --------------------------------------------------------------------
        // Domain must take the subscriber out of the registry before
        // calling close().
        // Dynamic removal:
        //     domain.closeSubscriber(subscriber.subscriber());
        // Global shutdown:
        //     Domain.takeFirstSubscriber()
        //         -> subscriber.close()
        // As of close() DOES unregister itself (unregisterSubscriber).
        // --------------------------------------------------------------------
        pub fn close(self: *Self) void {
            // Close contract: close() is SINGLE-USE and
            // destructive (like free()): first it UNREGISTERS (so the Domain no
            // longer holds references; the exclusive lock waits for in-flight
            // dispatches), then it stops the threads, frees resources and frees
            // the struct. Any later call on this pointer is UB, and calling
            // close() twice is UB as well.
            self.domain.unregisterSubscriber(self.subscriber());

            self.qm.close();

            self.deinit();
            self.domain.allocator.destroy(self);
        }

        // --------------------------------------------------------------------
        // ENQUEUE
        // --------------------------------------------------------------------
        // On success, QueueMgr takes ownership of the Msg.
        // On error, the caller keeps full ownership of the Msg.
        // --------------------------------------------------------------------
        pub fn enqueue(self: *Self, msg: Msg) !void {
            try self.qm.enqueue(msg);
        }

        // --------------------------------------------------------------------
        // INTERFACE
        // --------------------------------------------------------------------
        pub fn subscriber(self: *Self) ifcSubscriber {
            return ifcSubscriber.init(self);
        }
    };
}
