// ------------------------------------------------------------
// Auto-generated by k6b-genpubsub.
// Source proto: cctrol.proto
// Package: cctrol
// Safe pub/sub bindings.
// Generic safe pub/sub engine:
//   safe_pubsub.zig
// Safe message API:
//   cctrol_api.zig
// Raw pub/sub bindings remain available in:
//   cctrol_pubsub.zig
// Do not edit by hand unless you know what you are doing.
// ------------------------------------------------------------

const pubsub = @import("safe_pubsub.zig");
const ApiFile = @import("cctrol_api.zig");

// ============================================================================
// CCtrol
// ============================================================================
pub const CCtrol_Publisher =
    pubsub.SafePublisher(ApiFile.CCtrol, ApiFile.BinaraFormato);

pub const CCtrol_Subscriber =
    pubsub.SafeSubscriber(ApiFile.CCtrol, ApiFile.BinaraFormato);

// ============================================================================
// EstRemCtrol
// ============================================================================
pub const EstRemCtrol_Publisher =
    pubsub.SafePublisher(ApiFile.EstRemCtrol, ApiFile.BinaraFormato);

pub const EstRemCtrol_Subscriber =
    pubsub.SafeSubscriber(ApiFile.EstRemCtrol, ApiFile.BinaraFormato);

// ============================================================================
// EstMeteo
// ============================================================================
pub const EstMeteo_Publisher =
    pubsub.SafePublisher(ApiFile.EstMeteo, ApiFile.BinaraFormato);

pub const EstMeteo_Subscriber =
    pubsub.SafeSubscriber(ApiFile.EstMeteo, ApiFile.BinaraFormato);

// ============================================================================
// SnrTrafico
// ============================================================================
pub const SnrTrafico_Publisher =
    pubsub.SafePublisher(ApiFile.SnrTrafico, ApiFile.BinaraFormato);

pub const SnrTrafico_Subscriber =
    pubsub.SafeSubscriber(ApiFile.SnrTrafico, ApiFile.BinaraFormato);

// ============================================================================
// PanelInfoV
// ============================================================================
pub const PanelInfoV_Publisher =
    pubsub.SafePublisher(ApiFile.PanelInfoV, ApiFile.BinaraFormato);

pub const PanelInfoV_Subscriber =
    pubsub.SafeSubscriber(ApiFile.PanelInfoV, ApiFile.BinaraFormato);

// ============================================================================
// PanelBase
// ============================================================================
pub const PanelBase_Publisher =
    pubsub.SafePublisher(ApiFile.PanelBase, ApiFile.BinaraFormato);

pub const PanelBase_Subscriber =
    pubsub.SafeSubscriber(ApiFile.PanelBase, ApiFile.BinaraFormato);

// ============================================================================
// SenialInfo
// ============================================================================
pub const SenialInfo_Publisher =
    pubsub.SafePublisher(ApiFile.SenialInfo, ApiFile.BinaraFormato);

pub const SenialInfo_Subscriber =
    pubsub.SafeSubscriber(ApiFile.SenialInfo, ApiFile.BinaraFormato);

// ============================================================================
// TextoInfo
// ============================================================================
pub const TextoInfo_Publisher =
    pubsub.SafePublisher(ApiFile.TextoInfo, ApiFile.BinaraFormato);

pub const TextoInfo_Subscriber =
    pubsub.SafeSubscriber(ApiFile.TextoInfo, ApiFile.BinaraFormato);

