// ------------------------------------------------------------
// Auto-generated by k6b-genpubsub.
//
// Source proto: cctrol.proto
// Package: cctrol
//
// Do not edit by hand unless you know what you are doing.
// ------------------------------------------------------------

const pubsub = @import("generic_pubsub.zig");

const ProtoFile = @import("cctrol.zig");
const Pkg = ProtoFile.cctrol;

pub const CCtrol_Publisher =
    pubsub.GenericPublisher(Pkg.CCtrol, ProtoFile.BinaraFormato);

pub const CCtrol_Subscriber =
    pubsub.GenericSubscriber(Pkg.CCtrol, ProtoFile.BinaraFormato);

pub const EstRemCtrol_Publisher =
    pubsub.GenericPublisher(Pkg.EstRemCtrol, ProtoFile.BinaraFormato);

pub const EstRemCtrol_Subscriber =
    pubsub.GenericSubscriber(Pkg.EstRemCtrol, ProtoFile.BinaraFormato);

pub const EstMeteo_Publisher =
    pubsub.GenericPublisher(Pkg.EstMeteo, ProtoFile.BinaraFormato);

pub const EstMeteo_Subscriber =
    pubsub.GenericSubscriber(Pkg.EstMeteo, ProtoFile.BinaraFormato);

pub const SnrTrafico_Publisher =
    pubsub.GenericPublisher(Pkg.SnrTrafico, ProtoFile.BinaraFormato);

pub const SnrTrafico_Subscriber =
    pubsub.GenericSubscriber(Pkg.SnrTrafico, ProtoFile.BinaraFormato);

pub const PanelInfoV_Publisher =
    pubsub.GenericPublisher(Pkg.PanelInfoV, ProtoFile.BinaraFormato);

pub const PanelInfoV_Subscriber =
    pubsub.GenericSubscriber(Pkg.PanelInfoV, ProtoFile.BinaraFormato);

pub const PanelBase_Publisher =
    pubsub.GenericPublisher(Pkg.PanelBase, ProtoFile.BinaraFormato);

pub const PanelBase_Subscriber =
    pubsub.GenericSubscriber(Pkg.PanelBase, ProtoFile.BinaraFormato);

pub const SenialInfo_Publisher =
    pubsub.GenericPublisher(Pkg.SenialInfo, ProtoFile.BinaraFormato);

pub const SenialInfo_Subscriber =
    pubsub.GenericSubscriber(Pkg.SenialInfo, ProtoFile.BinaraFormato);

pub const TextoInfo_Publisher =
    pubsub.GenericPublisher(Pkg.TextoInfo, ProtoFile.BinaraFormato);

pub const TextoInfo_Subscriber =
    pubsub.GenericSubscriber(Pkg.TextoInfo, ProtoFile.BinaraFormato);

