const std = @import("std");

const parser = @import("parser.zig");

// ------------------------------------------------------------
// Public API
// ------------------------------------------------------------
// Generates:
//   <output_dir>/<proto_base_name>_pubsub.zig
//
// The generated file assumes it lives in the same directory as:
//   - generic_pubsub.zig
//   - <proto_base_name>.zig
//
// Example:
//   cctrol.proto
//       -> cctrol.zig
//       -> cctrol_pubsub.zig
//
// Generated imports:
//   const pubsub = @import("generic_pubsub.zig");
//   const ProtoFile = @import("cctrol.zig");
//   const Pkg = ProtoFile.cctrol;
//
// Only top-level messages are emitted. Nested/internal messages are
// intentionally ignored by parser.zig.
// ------------------------------------------------------------
pub fn writePubSubFile(allocator: std.mem.Allocator, summary: parser.ProtoSummary, output_dir: []const u8) !void {
    const output_file_name = try std.fmt.allocPrint(
        allocator,
        "{s}_pubsub.zig",
        .{summary.proto_base_name},
    );
    defer allocator.free(output_file_name);

    const output_path = try std.fs.path.join(
        allocator,
        &[_][]const u8{
            output_dir,
            output_file_name,
        },
    );
    defer allocator.free(output_path);

    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);

    try writeHeader(allocator, &buf, summary);
    for (summary.messages) |msg_name| {
        try writeMessageWrappers(allocator, &buf, msg_name);
    }

    const file = try std.fs.cwd().createFile(output_path, .{ .truncate = true });
    defer file.close();

    try file.writeAll(buf.items);
}

// ------------------------------------------------------------
// Generated file header
// ------------------------------------------------------------
fn writeHeader(allocator: std.mem.Allocator, buf: *std.ArrayList(u8), summary: parser.ProtoSummary) !void {
    try buf.print(allocator,
        \\// ------------------------------------------------------------
        \\// Auto-generated by k6b-genpubsub.
        \\//
        \\// Source proto: {s}.proto
        \\// Package: {s}
        \\//
        \\// Do not edit by hand unless you know what you are doing.
        \\// ------------------------------------------------------------
        \\
        \\const pubsub = @import("generic_pubsub.zig");
        \\
        \\const ProtoFile = @import("{s}.zig");
        \\
    , .{
        summary.proto_base_name,
        summary.package_name,
        summary.proto_base_name,
    });

    if (summary.package_name.len > 0) {
        try buf.print(allocator,
            \\const Pkg = ProtoFile.{s};
            \\
            \\
        , .{summary.package_name});
    } else {
        try buf.print(allocator,
            \\const Pkg = ProtoFile;
            \\
            \\
        , .{});
    }
}

// ------------------------------------------------------------
// Per-message wrappers
// ------------------------------------------------------------
// For each top-level message M, generate:
//   pub const M_Publisher =
//       pubsub.GenericPublisher(Pkg.M, ProtoFile.BinaraFormato);
//
//   pub const M_Subscriber =
//       pubsub.GenericSubscriber(Pkg.M, ProtoFile.BinaraFormato);
// ------------------------------------------------------------
fn writeMessageWrappers(allocator: std.mem.Allocator, buf: *std.ArrayList(u8), msg_name: []const u8) !void {
    try buf.print(allocator,
        \\pub const {s}_Publisher =
        \\    pubsub.GenericPublisher(Pkg.{s}, ProtoFile.BinaraFormato);
        \\
        \\pub const {s}_Subscriber =
        \\    pubsub.GenericSubscriber(Pkg.{s}, ProtoFile.BinaraFormato);
        \\
        \\
    , .{
        msg_name,
        msg_name,
        msg_name,
        msg_name,
    });
}
