// ------------------------------------------------------------
// Auto-generated by k6b-genpubsub.
// Source proto: Estacion.proto
// Package: demo1
// Raw pub/sub bindings.
// Generic pub/sub engine:
//   generic_pubsub.zig
// Raw message implementation:
//   Estacion.zig
// Do not edit by hand unless you know what you are doing.
// ------------------------------------------------------------

const pubsub = @import("generic_pubsub.zig");
const ProtoFile = @import("Estacion.zig");
const Pkg = ProtoFile.demo1;

// ============================================================================
// Estacion
// ============================================================================
pub const Estacion_Publisher =
    pubsub.GenericPublisher(Pkg.Estacion, ProtoFile.BinaraFormato);

pub const Estacion_Subscriber =
    pubsub.GenericSubscriber(Pkg.Estacion, ProtoFile.BinaraFormato);
