// ------------------------------------------------------------
// Auto-generated by k6b-genpubsub.
// Source proto: Estacion.proto
// Package: demo1
// Safe pub/sub bindings.
// Generic safe pub/sub engine:
//   safe_pubsub.zig
// Safe message API:
//   Estacion_api.zig
// Raw pub/sub bindings remain available in:
//   Estacion_pubsub.zig
// Do not edit by hand unless you know what you are doing.
// ------------------------------------------------------------

const pubsub = @import("safe_pubsub.zig");
const ApiFile = @import("Estacion_api.zig");

// ============================================================================
// Estacion
// ============================================================================
pub const Estacion_Publisher =
    pubsub.SafePublisher(ApiFile.Estacion, ApiFile.BinaraFormato);

pub const Estacion_Subscriber =
    pubsub.SafeSubscriber(ApiFile.Estacion, ApiFile.BinaraFormato);
