// ------------------------------------------------------------
// Auto-generated by k6b-genpubsub.
// Source proto: Bon.proto
// Package: demo4
// Safe pub/sub bindings.
// Generic safe pub/sub engine:
//   safe_pubsub.zig
// Safe message API:
//   Bon_api.zig
// Raw pub/sub bindings remain available in:
//   Bon_pubsub.zig
// Do not edit by hand unless you know what you are doing.
// ------------------------------------------------------------

const pubsub = @import("safe_pubsub.zig");
const ApiFile = @import("Bon_api.zig");

// ============================================================================
// Cia
// ============================================================================
pub const Cia_Publisher =
    pubsub.SafePublisher(ApiFile.Cia, ApiFile.BinaraFormato);

pub const Cia_Subscriber =
    pubsub.SafeSubscriber(ApiFile.Cia, ApiFile.BinaraFormato);

// ============================================================================
// Bon
// ============================================================================
pub const Bon_Publisher =
    pubsub.SafePublisher(ApiFile.Bon, ApiFile.BinaraFormato);

pub const Bon_Subscriber =
    pubsub.SafeSubscriber(ApiFile.Bon, ApiFile.BinaraFormato);

