// ------------------------------------------------------------
// Auto-generated by k6b-genpubsub.
// Source proto: Bon.proto
// Package: demo4
// Raw pub/sub bindings.
// Generic pub/sub engine:
//   generic_pubsub.zig
// Raw message implementation:
//   Bon.zig
// Do not edit by hand unless you know what you are doing.
// ------------------------------------------------------------

const pubsub = @import("generic_pubsub.zig");
const ProtoFile = @import("Bon.zig");
const Pkg = ProtoFile.demo4;

// ============================================================================
// Cia
// ============================================================================
pub const Cia_Publisher =
    pubsub.GenericPublisher(Pkg.Cia, ProtoFile.BinaraFormato);

pub const Cia_Subscriber =
    pubsub.GenericSubscriber(Pkg.Cia, ProtoFile.BinaraFormato);

// ============================================================================
// Bon
// ============================================================================
pub const Bon_Publisher =
    pubsub.GenericPublisher(Pkg.Bon, ProtoFile.BinaraFormato);

pub const Bon_Subscriber =
    pubsub.GenericSubscriber(Pkg.Bon, ProtoFile.BinaraFormato);

